# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "bbduk_trim_2pass"
description: Trim primers on unaligned FASTQs using two BBDUK passes
keywords:
  - trim
  - primer
  - bbduk
components:
  - bbmap/bbduk
input:
  - ch_reads:
      type: file
      description: |
        The input channel containing the BAM/CRAM/SAM files
        Structure: [ val(meta), path(bam) ]
      pattern: "*.{bam/cram/sam}"
## TODO nf-core: List all of the channels used as output with a descriptions and their structure
output:
  - bam:
      type: file
      description: |
        Channel containing BAM files
        Structure: [ val(meta), path(bam) ]
      pattern: "*.bam"
  - bai:
      type: file
      description: |
        Channel containing indexed BAM (BAI) files
        Structure: [ val(meta), path(bai) ]
      pattern: "*.bai"
  - csi:
      type: file
      description: |
        Channel containing CSI files
        Structure: [ val(meta), path(csi) ]
      pattern: "*.csi"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@smagala"
maintainers:
  - "@smagala"
